general {
    lock_cmd = pidof hyprlock || uwsm-app -- hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"
    inhibit_sleep = 2
}

listener {
    timeout = 120
    on-timeout = ddcutil -b 3 --sleep-multiplier 0 setvcp 10 0 & ddcutil -b 5 --sleep-multiplier 0 setvcp 10 0 &
    on-resume = ddcutil -b 3 --sleep-multiplier 0 setvcp 10 75 & ddcutil -b 5 --sleep-multiplier 0 setvcp 10 75 &
}

listener {
    timeout = 1800
    on-timeout = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = sleep 0.5 && hyprctl dispatch "hl.dsp.dpms({ action = 'off' })"
    on-resume = sleep 1 && hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"; for _ in {0..5}; do ddcutil -b 5 --sleep-multiplier 0 setvcp 10 75; sleep 2; done
}
